accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from accounts import views


urlpatterns = [
    url(r'^send_login_email$', views.send_login_email, name='send_login_email'),
    url(r'^login$', views.login, name='login'),
]

lists/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from lists import views

urlpatterns = [
    #path('admin/', admin.site.urls),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
    url(r'^(\d+)/add_item$', views.add_item, name='add_item'),
    url(r'^new$', views.new_list, name='new_list'),
]

superlists/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from lists import views
from accounts import urls as accounts_urls

urlpatterns = [
    #path('admin/', admin.site.urls),
    url(r'^$', views.home_page, name='home'),
    url(r'^lists/', include('lists.urls')),
    url(r'^accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
import uuid
from django.contrib import auth

auth.signals.user_logged_in.disconnect(auth.models.update_last_login)


class User(models.Model):
    email = models.EmailField()
    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'
    is_anonymous = False
    is_authenticated = True
    email = models.EmailField(unique=True)
    email = models.EmailField(primary_key=True)


class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4, max_length=40)

lists/models.py
from django.db import models


class List(models.Model):
    pass


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None, on_delete=models.PROTECT)

# Create your models here.

accounts/views.py
import sys
from django.urls import reverse
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.contrib import messages
from accounts.models import Token
from django.contrib import auth


def send_login_email(request):
    email = request.POST['email']
    token = Token.objects.create(email=email)
    url = request.build_absolute_uri(
        reverse('login') + '?token=' + str(token.uid)
    )
    message_body = f'Use this link to log in:\n\n{url}'

    send_mail(
        'Your login link for Superlists',
        message_body,
        'noreply@superlists',
        [email]
    )
    messages.success(
        request,
        # later
        # messages.SUCCESS,
        "Check your email, we've sent you a link you can use to log in."
    )
    return redirect('/')


def login(request):
    user = auth.authenticate(uid=request.GET.get('token'))
    if user:
        auth.login(request, user)
    return redirect('/')

lists/views.py
from django.shortcuts import redirect, render
from lists.models import Item, List
from django.http import HttpResponse
# Create your views here.


def home_page(request):
    item = Item()
    items = Item.objects.all()
    comment = get_comment(items.count())
    return render(request, 'homepage.html', {'comment': comment})


def get_comment(count):
    if count == 0:
        comment = "yey, waktunya berlibur"
    elif count < 5:
        comment = "sibuk tapi santai"
    else:
        comment = "oh tidak"
    return comment


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    item = Item()
    items = Item.objects.filter(list_id=list_id)
    print(items.count())
    comment = get_comment(items.count())
    return render(request, 'list.html', {'list': list_, 'comment': comment})


def new_list(request):
    list_ = List.objects.create()
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect('/lists/%d/' % (list_.id,))


def add_item(request, list_id):
    list_ = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect('/lists/%d/' % (list_.id,))

lists/templates/base.html
<html lang="en">

<head>
<div class="text-center">
<title>Ahmad Yazid Homepage</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
  <link href="/static/base.css" rel="stylesheet" media="screen">
  <h1>Ahmad Yazid</h1>
  <h2>1506722752</h2>
</div>
<head>

<body>

 <div class="container">
<form class="navbar-form navbar-right"
      method="POST"
      action="{% url 'send_login_email' %}">
 <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Superlists</a>
      <form class="navbar-form navbar-right" method="POST" action="#">
        <span>Enter email to log in:</span>
        <input class="form-control" name="email" type="text" />
        {% csrf_token %}
      </form>
    </div>
  </nav>

      {% if messages %}
        <div class="row">
          <div class="col-md-8">
            {% for message in messages %}
              {% if message.level_tag == 'success' %}
                <div class="alert alert-success">{{ message }}</div>
              {% else %}
                <div class="alert alert-warning">{{ message }}</div>
              {% endif %}
            {% endfor %}
          </div>
        </div>
      {% endif %}



     <div class="row">
        <div class="col-sm jumbotron">
          <div class="text-center">
           <h1 id="to_do_header">{% block to_do_header %}{% endblock %}</h1>
              <form method="POST" action="{% block form_action %}{% endblock %}">
              <input name="item_text" id="id_new_item" class="form-control input-lg" placeholder="Enter a to-do item"/>
                {% csrf_token %}
              </form>
          </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm">
            {% block table %}
            {% endblock %}
        </div>
          {% block comment %}
          {% endblock %}
      </div>

</div>
</body>


</html>

lists/templates/homepage.html
{% extends 'base.html' %}
{% block to_do_header %}Start a new To-Do list{% endblock %}
{% block form_action %}/lists/new{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block to_do_header %}Your To-Do list{% endblock %}

{% block form_action %}/lists/{{ list.id }}/add_item{% endblock %}


{% block table %}
    <table id="id_list_table" class="table">
      {% for item in list.item_set.all %}
          <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
      {% endfor %}
    </table>
{% endblock %}


{% block comment %}

<h1 id="comment">{{comment}}</h1>

{% endblock %}